<?php $this->layout('layout::default', ['title' => _('Servers')]) ?>

<h1><?= _('Servers') ?></h1>

<div class="tw-card">
    <?= $this->fetch('partial::link', [
        'label'   => _('Create server'),
        'icon'    => 'bi bi-plus-circle',
        'classes' => 'btn btn-primary',
        'href'    => $this->url('server.create'),
    ]) ?>

    <hr />

    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th><?= _('Name') ?></th>
            <th><?= _('IP address') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($servers as $server): ?>
            <tr>
                <td><?= $this->fetch('partial::link', [
                        'href'  => $this->url('server.edit', ['id' => $server->id]),
                        'label' => $server->name,
                    ]) ?></td>
                <td><?= $this->e($server->host) ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
