<?php $this->layout('layout::default', ['title' => _('Create team')]) ?>

<h1><?= _('Create team') ?></h1>

<?php $this->start('card-content') ?>
    <form action="<?= $this->url('team.create') ?>" method="post">
        <?= $this->fetch('partial::input/csrf') ?>

        <?= $this->fetch('partial::input/text', [
            'id'         => 'name',
            'label'      => _('Team name'),
            'autofocus'  => 'autofocus',
            'validation' => $validationBag ?? null,
        ]) ?>

        <div class="form-group">
            <label class="form-label"><?= _('Invite team members (optional)') ?></label>
            <?= $this->fetch('partial::team/email-fields', [
                'emails'     => $validationBag?->getArrayValueByName('emailsToInvite') ?: [''],
                'validation' => $validationBag ?? null,
            ]) ?>
        </div>

        <?= $this->fetch('partial::input/button', [
            'label' => _('Save'),
        ]) ?>

        <?= $this->fetch('partial::link', [
                'label' => _('Cancel'),
                'href' => $this->url('team'),
                'classes' => 'btn btn-secondary',
        ]) ?>

    </form>
<?php $this->stop() ?>
