<?php $this->layout('layout::default', ['title' => $this->t('Edit team')]) ?>

<h1><?= $this->t('Edit team') ?></h1>

<?php $this->start('card-content') ?>
    <form action="<?= $this->url('team.edit', ['id' => $team->id->toString()]) ?>" method="post">
        <?= $this->fetch('partial::input/csrf') ?>

        <?= $this->fetch('partial::input/text', [
            'id'         => 'name',
            'label'      => $this->t('Team name'),
            'autofocus'  => 'autofocus',
            'validation' => $validationBag,
        ]) ?>

        <div class="form-group">
            <label class="form-label"><?= $this->t('Team members') ?></label>
            <?= $this->fetch('partial::team/member-list', [
                'members'       => $members,
                'teamId'        => $team->id->toString(),
                'ownerId'       => $team->ownerId->toString(),
                'usersToRemove' => $validationBag->getArrayValueByName('usersToRemove'),
            ]) ?>
        </div>

        <div class="form-group">
            <label class="form-label"><?= $this->t('Invite more members (optional)') ?></label>
            <?= $this->fetch('partial::team/email-fields', [
                'emails'     => $validationBag->getArrayValueByName('emailsToInvite') ?: [''],
                'validation' => $validationBag,
            ]) ?>
        </div>

        <div class="d-flex gap-2">
            <?= $this->fetch('partial::input/button', [
                'label' => $this->t('Save'),
            ]) ?>
            <?= $this->fetch('partial::link', [
                    'label' => $this->t('Cancel'),
                    'href' => $this->url('server'),
                    'classes' => 'btn btn-secondary',
            ]) ?>
            <?php if ($canDelete): ?>
                <?= $this->fetch('partial::input/button', [
                    'classes'      => 'btn btn-outline-danger',
                    'icon'         => 'bi bi-trash3',
                    'type'         => 'button',
                    'dataBsToggle' => 'modal',
                    'dataBsTarget' => '#tw-delete-team-modal',
                ]) ?>
            <?php endif ?>
        </div>

    </form>
<?php $this->stop() ?>

<?php if ($canDelete): ?>
    <?= $this->fetch('partial::modal', [
        'id'            => 'tw-delete-team-modal',
        'header'        => $this->t('Delete team'),
        'body'          => $this->t('Are you sure you want to delete the team {name}? This action cannot be undone. Deleting a team will delete all associated resources too!', ['name' => '<strong>' . $this->e($team->name) . '</strong>']),
        'actionUrl'     => $this->url('team.delete', ['id' => $team->id->toString()]),
        'actionLabel'   => $this->t('Delete team'),
        'actionClasses' => 'btn btn-danger',
        'actionIcon'    => 'bi bi-trash3',
    ]) ?>
<?php endif ?>
