<?php $this->layout('layout::default', ['title' => _('Teams')]) ?>

<h1><?= _('Teams') ?></h1>

<div class="tw-card">
    <?= $this->fetch('partial::link', [
        'label'   => _('Create Team'),
        'icon'    => 'bi bi-plus-circle',
        'classes' => 'btn btn-primary',
        'href'    => $this->url('team.create'),
    ]) ?>

    <hr />

    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th><?= _('Name') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($teams as $team): ?>
            <tr>
                <td><?= $this->fetch('partial::link', [
                        'href'  => $this->url('team.show', ['id' => $team->id]),
                        'label' => $team->name,
                    ]) ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
