══════════════════
 T R A G W E R K
══════════════════


<?= $this->section('content') ?>


──────────────────


<?= $this->t('Tragwerk — Simple hosting for PHP applications.') ?>

<?= $this->t('Imprint:') ?> <?= $this->serverurl($this->url('imprint')) ?>

<?= $this->t('Privacy Policy:') ?> <?= $this->serverurl($this->url('privacy-policy')) ?>

<?= $this->t('Terms & Conditions:') ?> <?= $this->serverurl($this->url('terms-and-conditions')) ?>


<?= $this->t('This is an automated message — please do not reply to this email.') ?>
