<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="author" content="Columbus Interactive, www.columbus-interactive.de" />
        <meta name="viewport" content="width=device-width; initial-scale=1.0;" />
        <meta content="telephone=no" name="format-detection" />
        <title>La Pinta</title>
        <style type="text/css">
            * {
                -webkit-font-smoothing: antialiased;
                -webkit-text-size-adjust:none;
            }

            body {
                font-family: Arial, sans-serif;
                mso-line-height-rule: exactly;
            }

            table {
                border-collapse: collapse;
                mso-table-lspace: 0px;
                mso-table-rspace: 0px;
            }

            a {
                text-decoration: none;
                color: #0000ff;
                font-weight: bold;
            }

            a:hover {
                text-decoration: underline;
                color: #0000ff;
                font-weight: bold;
            }
        </style>
    </head>

    <body style="margin: 12px 12px 12px 12px; padding: 0px 0px 0px 0px; -webkit-text-size-adjust: none;" bgcolor="#ffffff">
        <div style="font-size: 20px; font-weight: bold;">
            Tragwerk
        </div>
        <br /><br />

        {% block content %}{% endblock %}
        <br />
    </body>
</html>
