<?php $this->layout('layout::default', ['title' => $this->t('Create credential')]) ?>

<h1><?= $this->t('Create credential') ?></h1>

<?php $this->start('card-content') ?>
    <form action="<?= $this->url('credential.create') ?>" method="post">
        <?= $this->fetch('partial::input/csrf') ?>
        <?= $this->fetch('partial::input/text', [
            'id'         => 'name',
            'label'      => $this->t('Name'),
            'autofocus'  => 'autofocus',
            'validation' => $validationBag ?? null,
        ]) ?>
        <?= $this->fetch('partial::input/text', [
            'id'         => 'username',
            'label'      => $this->t('Username'),
            'validation' => $validationBag ?? null,
        ]) ?>
        <?= $this->fetch('partial::input/textarea', [
            'id'         => 'privateKey',
            'label'      => $this->t('Private key'),
            'validation' => $validationBag ?? null,
        ]) ?>
        <?= $this->fetch('partial::input/button', [
            'label' => $this->t('Save'),
        ]) ?>
        <?= $this->fetch('partial::link', [
            'label'   => $this->t('Cancel'),
            'href'    => $this->url('credential'),
            'classes' => 'btn btn-secondary',
        ]) ?>
    </form>
<?php $this->stop() ?>
