<?php $this->layout('layout::default', ['title' => _('Create credential')]) ?>

<h1><?= _('Create credential') ?></h1>

<?php $this->start('card-content') ?>
    <form action="<?= $this->url('credential.create') ?>" method="post">
        <?= $this->fetch('partial::input/csrf') ?>
        <?= $this->fetch('partial::input/text', [
            'id'         => 'name',
            'label'      => _('Name'),
            'autofocus'  => 'autofocus',
            'validation' => $validationBag ?? null,
        ]) ?>
        <?= $this->fetch('partial::input/text', [
            'id'         => 'username',
            'label'      => _('Username'),
            'validation' => $validationBag ?? null,
        ]) ?>
        <?= $this->fetch('partial::input/textarea', [
            'id'         => 'privateKey',
            'label'      => _('Private key'),
            'validation' => $validationBag ?? null,
        ]) ?>
        <?= $this->fetch('partial::input/button', [
            'label' => _('Save'),
        ]) ?>
        <?= $this->fetch('partial::link', [
            'label'   => _('Cancel'),
            'href'    => $this->url('credential'),
            'classes' => 'btn btn-secondary',
        ]) ?>
    </form>
<?php $this->stop() ?>
