<?php $this->layout('layout::default', ['title' => $this->t('Credentials')]) ?>

<h1><?= $this->t('Credentials') ?></h1>

<div class="tw-card">
    <?= $this->fetch('partial::link', [
        'label'   => $this->t('Create credential'),
        'icon'    => 'bi bi-plus-circle',
        'classes' => 'btn btn-primary',
        'href'    => $this->url('credential.create'),
    ]) ?>

    <hr />

    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th><?= $this->t('Name') ?></th>
            <th><?= $this->t('Username') ?></th>
            <th><?= $this->t('SSH Key') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($credentials as $credential): ?>
            <tr>
                <td><?= $this->fetch('partial::link', [
                        'href'  => $this->url('credential.show', ['id' => $credential->id]),
                        'label' => $credential->name,
                    ]) ?></td>
                <td><?= $this->e($credential->username) ?></td>
                <td>
                    <?php if ($credential->privateKey !== null): ?>
                        <i class="bi bi-check-circle-fill text-success"></i>
                    <?php else: ?>
                        <i class="bi bi-x-circle text-secondary"></i>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
