<?php
/**
 * @var \Tragwerk\Domain\Entity\Project $project
 * @var \Tragwerk\Domain\Entity\Server  $server
 * @var \Tragwerk\Domain\Entity\Team    $team
 */
?>
<table class="table table-borderless mb-0">
    <tbody>
        <tr>
            <th class="w-25 text-body-secondary fw-normal"><?= _('Name') ?></th>
            <td><?= $this->e($project->name) ?></td>
        </tr>
        <tr>
            <th class="text-body-secondary fw-normal"><?= _('Server') ?></th>
            <td>
                <?= $this->fetch('partial::link', [
                    'href'  => $this->url('server.show', ['id' => $server->id->toString()]),
                    'label' => $server->name,
                ]) ?>
            </td>
        </tr>
        <tr>
            <th class="text-body-secondary fw-normal"><?= _('Team') ?></th>
            <td>
                <?= $this->fetch('partial::link', [
                    'href'  => $this->url('team.show', ['id' => $team->id->toString()]),
                    'label' => $team->name,
                ]) ?>
            </td>
        </tr>
        <tr>
            <th class="text-body-secondary fw-normal"><?= _('Created') ?></th>
            <td><?= $this->e($project->createdAt->format('Y-m-d H:i')) ?></td>
        </tr>
        <tr>
            <th class="text-body-secondary fw-normal"><?= _('Updated') ?></th>
            <td><?= $this->e($project->updatedAt->format('Y-m-d H:i')) ?></td>
        </tr>
    </tbody>
</table>
