version: "3"

server:
  command: "php bin/server"

http:
  address: 0.0.0.0:${PORT:-80}
  max_request_size: ${RR_MAX_REQUEST_SIZE:-64}
  pool:
    num_workers: ${RR_NUM_WORKERS:-4}
    supervisor:
      exec_ttl: 60s
      max_worker_memory: ${RR_MAX_WORKER_MEMORY:-128}

logs:
  mode: production
  level: error
