memory_limit=-1
date.timezone=UTC
expose_php=0

# Errors
error_reporting=E_ALL ^ E_DEPRECATED
display_errors=0
display_startup_errors=0
log_errors=1
error_log=php://stderr

# OPcache
opcache.enable=1
opcache.enable_cli=1

# Xdebug
;xdebug.mode=off;
xdebug.mode=debug,develop
xdebug.start_with_request=yes
xdebug.start_upon_error=no
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey=PHPSTORM

# PCOV
pcov.enabled=0
