<?php

use Tragwerk\Domain\ValueObject\TimestampImmutable;

assert(isset($date) && $date instanceof TimestampImmutable);

$dateFormat = 'Y-m-d\\TH:iP';
$formatter = 'datetime';

if (($numerical ?? false) === true) {
    $formatter = 'datetime-numerical';
}

?>
<time datetime="<?= $this->e($date->format($dateFormat)) ?>" title="<?= $this->e($date->format($dateFormat)) ?>" data-formatter="<?= $formatter ?>"
      <?php if(($classes ?? null) !== null): ?>class="<?= $classes ?>"<?php endif ?>>
    <?= $this->e($date->format($dateFormat)) ?>
</time>
