<?php
$links = [
        [
                'include' => 'partial::link',
                'label' => _('Servers'),
                'href' => $this->url('server'),
                'classes' => 'nav-link bi bi-server',
        ],
        [
                'include' => 'partial::link',
                'label' => _('Projects'),
                'href' => $this->url('project'),
                'classes' => 'nav-link bi bi-folder2-open',
        ],
];
?>
<ul class="nav flex-column">
    <?php foreach ($links as $l) printf('%s', $this->fetch($l['include'], $l));  ?>
</ul>