<?php $this->layout('layout::default', ['title' => $this->t('Create project')]) ?>

<h1><?= $this->t('Create project') ?></h1>

<?php $this->start('card-content') ?>
    <form action="<?= $this->url('project.create') ?>" method="post">
        <?= $this->fetch('partial::input/csrf') ?>

        <?= $this->fetch('partial::input/text', [
            'id'         => 'name',
            'label'      => $this->t('Project name'),
            'autofocus'  => 'autofocus',
            'validation' => $validationBag ?? null,
        ]) ?>

        <?php
            $serverOptions = [];
            foreach ($servers as $server) {
                $serverOptions[$server->id->toString()] = $server->name;
            }
        ?>
        <?= $this->fetch('partial::input/select', [
            'id'                 => 'serverId',
            'label'              => $this->t('Server'),
            'validation'         => $validationBag ?? null,
            'options'            => $serverOptions,
            'defaultOptionLabel' => $this->t('— select a server —'),
        ]) ?>

        <div class="d-flex gap-2">
            <?= $this->fetch('partial::input/button', [
                'label' => $this->t('Save'),
            ]) ?>

            <?= $this->fetch('partial::link', [
                'label'   => $this->t('Cancel'),
                'href'    => $this->url('project'),
                'classes' => 'btn btn-secondary',
            ]) ?>
        </div>

    </form>
<?php $this->stop() ?>
