<?php
/** @var \Tragwerk\Domain\Entity\Project $project */
$this->layout('layout::default', ['title' => _('Edit project')]);
?>

<h1><?= _('Edit project') ?></h1>

<?php $this->start('card-content') ?>
    <form action="<?= $this->url('project.edit', ['id' => $project->id->toString()]) ?>" method="post">
        <?= $this->fetch('partial::input/csrf') ?>

        <?= $this->fetch('partial::input/text', [
            'id'         => 'name',
            'label'      => _('Project name'),
            'autofocus'  => 'autofocus',
            'validation' => $validationBag,
        ]) ?>

        <?php
            $serverOptions = [];
            foreach ($servers as $server) {
                $serverOptions[$server->id->toString()] = $server->name;
            }
        ?>
        <?= $this->fetch('partial::input/select', [
            'id'           => 'serverId',
            'label'        => _('Server'),
            'validation'   => $validationBag,
            'options'      => $serverOptions,
            'defaultValue' => $validationBag->getValueByName('serverId'),
        ]) ?>

        <div class="d-flex gap-2">
            <?= $this->fetch('partial::input/button', [
                'label' => _('Save'),
            ]) ?>

            <?= $this->fetch('partial::link', [
                'label'   => _('Cancel'),
                'href'    => $this->url('project.show', ['id' => $project->id->toString()]),
                'classes' => 'btn btn-secondary',
            ]) ?>

            <?= $this->fetch('partial::input/button', [
                'classes'      => 'btn btn-outline-danger',
                'icon'         => 'bi bi-trash3',
                'type'         => 'button',
                'dataBsToggle' => 'modal',
                'dataBsTarget' => '#tw-delete-project-modal',
            ]) ?>
        </div>

    </form>
<?php $this->stop() ?>

<?= $this->fetch('partial::modal', [
    'id'            => 'tw-delete-project-modal',
    'header'        => _('Delete project'),
    'body'          => sprintf(
        _('Are you sure you want to delete the project %s? This action cannot be undone.'),
        '<strong>' . $this->e($project->name) . '</strong>',
    ),
    'actionUrl'     => $this->url('project.delete', ['id' => $project->id->toString()]),
    'actionLabel'   => _('Delete project'),
    'actionClasses' => 'btn btn-danger',
    'actionIcon'    => 'bi bi-trash3',
]) ?>
