<?php $this->layout('layout::default', ['title' => $this->t('Projects')]) ?>

<h1><?= $this->t('Projects') ?></h1>

<div class="tw-card">
    <?= $this->fetch('partial::link', [
        'label'   => $this->t('Create Project'),
        'icon'    => 'bi bi-plus-circle',
        'classes' => 'btn btn-primary',
        'href'    => $this->url('project.create'),
    ]) ?>

    <hr />

    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th><?= $this->t('Name') ?></th>
            <th><?= $this->t('Server') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($projects as $project): ?>
            <tr>
                <td><?= $this->fetch('partial::link', [
                        'href'  => $this->url('project.show', ['id' => $project->id->toString()]),
                        'label' => $project->name,
                    ]) ?></td>
                <td><?php $server = $servers[$project->serverId->toString()] ?? null ?>
                    <?php if ($server !== null): ?>
                        <?= $this->fetch('partial::link', [
                            'href'  => $this->url('server.show', ['id' => $server->id->toString()]),
                            'label' => $server->name,
                        ]) ?>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
