<?php $this->layout('layout::mail') ?>
<?= $user->firstname ?>,

<?= $this->t('You requested a password reset for your Tragwerk account. Click the link below to set a new password.') ?>

<?= $this->serverurl($this->url('passwordReset.apply', ['token' => $passwordReset->token])) ?>

<?= $this->t('This link expires in 2 hours. If you did not request a password reset, you can ignore this email.') ?>
