{% extends '@layout/mail.twig' %}

{% set meta = {title: t('mail.passwordReset.subject')} %}

{% block content %}

    {{ t('mail.greeting {name}', {name: user.fullName}) }}<br />
    <br />

    {{ t('mail.passwordReset.body') }}<br />
    <br />

    <a href="{{ absolute_url(path("passwordReset.apply", {passwordResetId: passwordReset.id}, {token: passwordReset.token.toString})) }}" target="_blank">
        {{ t('action.resetPassword') }}
    </a>

{% endblock %}
