<?php $this->layout('layout::mail') ?>
<?= $this->e($user->firstname) ?>,<br /><br />

<?= $this->t('Thank you for registering with Tragwerk. Please confirm your email address by clicking the link below.') ?><br /><br />

<a href="<?= $this->serverurl($this->url('email.confirm', ['token' => $confirmation->token])) ?>">
    <?= $this->t('Confirm email address') ?>
</a><br /><br />

<?= $this->t('This link expires in 24 hours.') ?>
