<?php assert(isset($label) && is_string($label)); ?>
<button class="<?= isset($classes) ? $this->e($classes) : 'btn btn-primary' ?>"
        type="<?= $type ?? 'submit' ?>"
        <?php if (($id ?? null) !== null):?>id="<?= $this->e($id) ?>"<?php endif; ?>
        <?php if (($name ?? null) !== null):?>name="<?= $this->e($name) ?>"<?php endif; ?>
        <?php if (($title ?? null) !== null):?>title="<?= $this->e($title) ?>"<?php endif; ?>
        <?php if (($form ?? null) !== null):?>form="<?= $this->e($form) ?>"<?php endif; ?>
        <?php if (($formAction ?? null) !== null):?>formaction="<?= $this->e($formAction) ?>"<?php endif; ?>
        <?php if (($formMethod ?? null) !== null):?>formmethod="<?= $this->e($formMethod) ?>"<?php endif; ?>
        <?php if (($value ?? null) !== null):?>value="<?= $this->e($value) ?>"<?php endif; ?>
        <?php if (($disabled ?? false) !== false):?>disabled<?php endif; ?>
><?= $this->e($label) ?></button>
